### ISSUE TITLE
validator didn't catch malformed string in "comments"

### ISSUE THREAD

**Issue by neuromusic** [chanzuckerberg/napari-hub-collections#29]
#27 fixed errors introduced in #25 where a colon in the "comments" field caused it to be parsed as a key:value pair instead of a string

however, the changes in #25 passed verification

our current schema for this field is

``` Python
class Comment(ConstrainedStr):
    max_length = 300
```

https://github.com/chanzuckerberg/napari-hub-collections/blob/main/validation/schema.py#L10-L11

why did this pass validation?

Documentation: https://pydantic-docs.helpmanual.io/usage/models/

Todo:
- edge cases (more than 300 characters, invalid data type, etc) 
- base cases (expected to be validated correctly, per yaml files provided in the repo)

**Comment by klai95** [comment]
As of now, II have fnished writing up a few test cases today per the todo list above. One of the test cases I have written up does behave the way I want to (Scanner Error from the additional : in the yaml file)! Right now, the gap I am trying to figure out is why I am able to reproduce the error in the way that I want to, but the malformed string didn’t get caught in [#25](https://github.com/chanzuckerberg/napari-hub-collections/pull/25/files), so that is my next step.

**Comment by klai95** [comment]
PR is here: https://github.com/chanzuckerberg/napari-hub-collections/pull/36
